// <auto-generated />
using System;
using EMua.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EMua.Migrations
{
    [DbContext(typeof(EMuaDbContext))]
    [Migration("20260915171831_InitialPostgreSql")]
    partial class InitialPostgreSql
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EMua.Models.Database.BaoCao", b =>
                {
                    b.Property<int>("MaBaoCao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaBaoCao"));

                    b.Property<string>("DuLieu")
                        .HasColumnType("text");

                    b.Property<string>("LoaiBaoCao")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("NgayBaoCao")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("MaBaoCao")
                        .HasName("PK__BaoCao__25A9188CF7650BAA");

                    b.ToTable("BaoCao");
                });

            modelBuilder.Entity("EMua.Models.Database.BienTheSanPham", b =>
                {
                    b.Property<int>("MaBienThe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaBienThe"));

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("MaSanPham")
                        .HasColumnType("integer");

                    b.Property<string>("MauSac")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PhienBan")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("integer");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Còn hàng");

                    b.HasKey("MaBienThe")
                        .HasName("PK__BienTheS__3987CEF598B5B7D6");

                    b.HasIndex(new[] { "MaSanPham" }, "IX_BienTheSanPham_MaSanPham");

                    b.ToTable("BienTheSanPham");
                });

            modelBuilder.Entity("EMua.Models.Database.ChiTietDonHang", b =>
                {
                    b.Property<int>("MaChiTietDonHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaChiTietDonHang"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("MaBienThe")
                        .HasColumnType("integer");

                    b.Property<int>("MaDonHang")
                        .HasColumnType("integer");

                    b.Property<int>("SoLuong")
                        .HasColumnType("integer");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("MaChiTietDonHang")
                        .HasName("PK__ChiTietD__835ED13B4D53BB16");

                    b.HasIndex("MaDonHang");

                    b.HasIndex(new[] { "MaBienThe" }, "IX_ChiTietDonHang_MaBienThe");

                    b.ToTable("ChiTietDonHang");
                });

            modelBuilder.Entity("EMua.Models.Database.ChiTietGioHang", b =>
                {
                    b.Property<int>("MaChiTietGioHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaChiTietGioHang"));

                    b.Property<int>("MaBienThe")
                        .HasColumnType("integer");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("integer");

                    b.Property<DateTime>("NgayThem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("SoLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("MaChiTietGioHang")
                        .HasName("PK__ChiTietG__BBF4749877F09C5C");

                    b.HasIndex("MaBienThe");

                    b.HasIndex(new[] { "MaNguoiDung", "MaBienThe" }, "UQ_ChiTietGioHang")
                        .IsUnique();

                    b.ToTable("ChiTietGioHang");
                });

            modelBuilder.Entity("EMua.Models.Database.CuocHoiThoaiAi", b =>
                {
                    b.Property<int>("MaCuocHoiThoai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaCuocHoiThoai"));

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("TieuDe")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("MaCuocHoiThoai")
                        .HasName("PK__CuocHoiT__3707D875B03839C0");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("CuocHoiThoaiAI");
                });

            modelBuilder.Entity("EMua.Models.Database.DanhGiaSanPham", b =>
                {
                    b.Property<int>("MaDanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaDanhGia"));

                    b.Property<string>("BinhLuan")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("MaDonHang")
                        .HasColumnType("integer");

                    b.Property<int?>("MaNguoiDung")
                        .HasColumnType("integer");

                    b.Property<int?>("MaSanPham")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("NgayDanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("SoLuongSao")
                        .HasColumnType("integer");

                    b.Property<bool?>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.HasKey("MaDanhGia")
                        .HasName("PK__DanhGiaS__AA9515BFCBF70C5B");

                    b.HasIndex("MaDonHang");

                    b.HasIndex("MaSanPham");

                    b.HasIndex(new[] { "MaNguoiDung", "MaSanPham" }, "UQ_DanhGia_User_Product")
                        .IsUnique()
                        .HasFilter("\"MaNguoiDung\" IS NOT NULL AND \"MaSanPham\" IS NOT NULL");

                    b.ToTable("DanhGiaSanPham");
                });

            modelBuilder.Entity("EMua.Models.Database.DanhMucSanPham", b =>
                {
                    b.Property<int>("MaDanhMuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaDanhMuc"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("TenDanhMuc")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TrangThaiDanhMuc")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("MaDanhMuc")
                        .HasName("PK__DanhMucS__B37508871346CE70");

                    b.ToTable("DanhMucSanPham");
                });

            modelBuilder.Entity("EMua.Models.Database.DonHang", b =>
                {
                    b.Property<int>("MaDonHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaDonHang"));

                    b.Property<string>("DiaChiNhanHang")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("HoTenNhanHang")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("MaKhuyenMai")
                        .HasColumnType("integer");

                    b.Property<int?>("MaNguoiDung")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("NgayDat")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PhuongThucVanChuyen")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SoDienThoaiNhanHang")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<decimal?>("TongTien")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<string>("TrangThaiDonHang")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Chờ xử lý");

                    b.HasKey("MaDonHang")
                        .HasName("PK__DonHang__129584AD88A83EF4");

                    b.HasIndex("MaKhuyenMai");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("DonHang");
                });

            modelBuilder.Entity("EMua.Models.Database.HoaDon", b =>
                {
                    b.Property<int>("MaHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaHoaDon"));

                    b.Property<int>("MaDonHang")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("NgayLapHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal?>("TongTien")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<string>("TrangThaiHoaDon")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Đã lập");

                    b.HasKey("MaHoaDon")
                        .HasName("PK__HoaDon__835ED13BE1E4A10D");

                    b.HasIndex(new[] { "MaDonHang" }, "UQ_HoaDon_MaDonHang")
                        .IsUnique();

                    b.ToTable("HoaDon");
                });

            modelBuilder.Entity("EMua.Models.Database.KhuyenMai", b =>
                {
                    b.Property<int>("MaKhuyenMai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaKhuyenMai"));

                    b.Property<decimal?>("GiaTriDonHangToiThieu")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<decimal>("GiaTriGiam")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<string>("LoaiGiamGia")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("MaCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("NgayBatDau")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("integer");

                    b.Property<string>("TenKhuyenMai")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.HasKey("MaKhuyenMai")
                        .HasName("PK__KhuyenMa__6F56B3BD8771E9E5");

                    b.HasIndex(new[] { "MaCode" }, "UQ__KhuyenMa__152C7C5CF41E5F9B")
                        .IsUnique();

                    b.ToTable("KhuyenMai");
                });

            modelBuilder.Entity("EMua.Models.Database.LichSuVanChuyen", b =>
                {
                    b.Property<int>("MaLichSu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaLichSu"));

                    b.Property<string>("DiaDiem")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("HinhAnhNguoiNhan")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("MaDonHang")
                        .HasColumnType("integer");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("ThoiGian")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("MaLichSu")
                        .HasName("PK__LichSuVa__C443222A60038AB5");

                    b.HasIndex("MaDonHang");

                    b.ToTable("LichSuVanChuyen");
                });

            modelBuilder.Entity("EMua.Models.Database.NguoiDung", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaNguoiDung"));

                    b.Property<string>("AnhDaiDien")
                        .HasColumnType("text");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("MaQuyen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3);

                    b.Property<string>("MatKhau")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("TenDangNhap")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TenNguoiDung")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.HasKey("MaNguoiDung")
                        .HasName("PK__NguoiDun__C539D76221D1D8FC");

                    b.HasIndex(new[] { "Email" }, "IX_NguoiDung_Email");

                    b.HasIndex(new[] { "MaQuyen" }, "IX_NguoiDung_MaQuyen");

                    b.HasIndex(new[] { "TenNguoiDung" }, "IX_NguoiDung_TenNguoiDung");

                    b.HasIndex(new[] { "Email" }, "UQ_NguoiDung_Email")
                        .IsUnique()
                        .HasFilter("\"Email\" IS NOT NULL");

                    b.HasIndex(new[] { "TenDangNhap" }, "UQ_NguoiDung_TenDangNhap")
                        .IsUnique()
                        .HasFilter("\"TenDangNhap\" IS NOT NULL");

                    b.ToTable("NguoiDung");
                });

            modelBuilder.Entity("EMua.Models.Database.PhanQuyen", b =>
                {
                    b.Property<int>("MaQuyen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaQuyen"));

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("TenQuyen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("MaQuyen")
                        .HasName("PK__PhanQuye__1D4B7ED47D31A58F");

                    b.HasIndex(new[] { "TenQuyen" }, "UQ__PhanQuye__5637EE792105E491")
                        .IsUnique();

                    b.ToTable("PhanQuyen");
                });

            modelBuilder.Entity("EMua.Models.Database.SanPham", b =>
                {
                    b.Property<int>("MaSanPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaSanPham"));

                    b.Property<string>("BaoHanh")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("GiaGoc")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<int?>("MaDanhMuc")
                        .HasColumnType("integer");

                    b.Property<int>("MaThuongHieu")
                        .HasColumnType("integer");

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("TenSanPham")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ThongSoKyThuat")
                        .HasColumnType("text");

                    b.Property<string>("TrangThaiSanPham")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Còn hàng");

                    b.HasKey("MaSanPham")
                        .HasName("PK__SanPham__FAC7442D8E7CBCF5");

                    b.HasIndex("MaDanhMuc");

                    b.HasIndex(new[] { "MaThuongHieu" }, "IX_SanPham_MaThuongHieu");

                    b.ToTable("SanPham");
                });

            modelBuilder.Entity("EMua.Models.Database.SanPhamHinhAnh", b =>
                {
                    b.Property<int>("MaAnh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaAnh"));

                    b.Property<string>("DuongDanAnh")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("LaAnhChinh")
                        .HasColumnType("boolean");

                    b.Property<int>("MaSanPham")
                        .HasColumnType("integer");

                    b.Property<int>("ThuTu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("MaAnh")
                        .HasName("PK__SanPhamH__356240DF6D083CA7");

                    b.HasIndex("MaSanPham");

                    b.ToTable("SanPhamHinhAnh");
                });

            modelBuilder.Entity("EMua.Models.Database.ThanhToan", b =>
                {
                    b.Property<int>("MaThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaThanhToan"));

                    b.Property<int>("MaDonHang")
                        .HasColumnType("integer");

                    b.Property<string>("MaGiaoDich")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("NgayThanhToan")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("PhuongThuc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Chờ thanh toán");

                    b.HasKey("MaThanhToan")
                        .HasName("PK__ThanhToa__D4B25844E085DA97");

                    b.HasIndex("MaDonHang");

                    b.ToTable("ThanhToan");
                });

            modelBuilder.Entity("EMua.Models.Database.ThuongHieu", b =>
                {
                    b.Property<int>("MaThuongHieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaThuongHieu"));

                    b.Property<string>("Logo")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TenThuongHieu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.HasKey("MaThuongHieu")
                        .HasName("PK__ThuongHi__A3733E2C0EF3AC57");

                    b.HasIndex(new[] { "TenThuongHieu" }, "UQ__ThuongHi__98D6A834D059DBAD")
                        .IsUnique();

                    b.ToTable("ThuongHieu");
                });

            modelBuilder.Entity("EMua.Models.Database.TinNhanAi", b =>
                {
                    b.Property<int>("MaTinNhan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaTinNhan"));

                    b.Property<int>("MaCuocHoiThoai")
                        .HasColumnType("integer");

                    b.Property<DateTime>("NgayGui")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("MaTinNhan")
                        .HasName("PK__TinNhanA__E5B3062ACADFFD71");

                    b.HasIndex("MaCuocHoiThoai");

                    b.ToTable("TinNhanAI");
                });

            modelBuilder.Entity("EMua.Models.Database.TuCam", b =>
                {
                    b.Property<int>("MaTuCam")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaTuCam"));

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.HasKey("MaTuCam")
                        .HasName("PK__TuCam__B89513110632111A");

                    b.HasIndex(new[] { "NoiDung" }, "UQ__TuCam__C69AFF423679873D")
                        .IsUnique();

                    b.ToTable("TuCam");
                });

            modelBuilder.Entity("EMua.Models.Database.YeuThich", b =>
                {
                    b.Property<int>("MaYeuThich")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaYeuThich"));

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("integer");

                    b.Property<int>("MaSanPham")
                        .HasColumnType("integer");

                    b.Property<DateTime>("NgayThem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("MaYeuThich")
                        .HasName("PK__YeuThich__B9007E4CB6025510");

                    b.HasIndex("MaSanPham");

                    b.HasIndex(new[] { "MaNguoiDung", "MaSanPham" }, "UQ_YeuThich")
                        .IsUnique();

                    b.ToTable("YeuThich");
                });

            modelBuilder.Entity("EMua.Models.Database.BienTheSanPham", b =>
                {
                    b.HasOne("EMua.Models.Database.SanPham", "MaSanPhamNavigation")
                        .WithMany("BienTheSanPhams")
                        .HasForeignKey("MaSanPham")
                        .IsRequired()
                        .HasConstraintName("FK_BienTheSanPham_SanPham");

                    b.Navigation("MaSanPhamNavigation");
                });

            modelBuilder.Entity("EMua.Models.Database.ChiTietDonHang", b =>
                {
                    b.HasOne("EMua.Models.Database.BienTheSanPham", "MaBienTheNavigation")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("MaBienThe")
                        .IsRequired()
                        .HasConstraintName("FK_ChiTietDonHang_BienThe");

                    b.HasOne("EMua.Models.Database.DonHang", "MaDonHangNavigation")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("MaDonHang")
                        .IsRequired()
                        .HasConstraintName("FK_CTDH_DonHang");

                    b.Navigation("MaBienTheNavigation");

                    b.Navigation("MaDonHangNavigation");
                });

            modelBuilder.Entity("EMua.Models.Database.ChiTietGioHang", b =>
                {
                    b.HasOne("EMua.Models.Database.BienTheSanPham", "MaBienTheNavigation")
                        .WithMany("ChiTietGioHangs")
                        .HasForeignKey("MaBienThe")
                        .IsRequired()
                        .HasConstraintName("FK_ChiTietGioHang_BienThe");

                    b.HasOne("EMua.Models.Database.NguoiDung", "MaNguoiDungNavigation")
                        .WithMany("ChiTietGioHangs")
                        .HasForeignKey("MaNguoiDung")
                        .IsRequired()
                        .HasConstraintName("FK_ChiTietGioHang_NguoiDung");

                    b.Navigation("MaBienTheNavigation");

                    b.Navigation("MaNguoiDungNavigation");
                });

            modelBuilder.Entity("EMua.Models.Database.CuocHoiThoaiAi", b =>
                {
                    b.HasOne("EMua.Models.Database.NguoiDung", "MaNguoiDungNavigation")
                        .WithMany("CuocHoiThoaiAis")
                        .HasForeignKey("MaNguoiDung")
                        .IsRequired()
                        .HasConstraintName("FK_CuocHoiThoaiAI_NguoiDung");

                    b.Navigation("MaNguoiDungNavigation");
                });

            modelBuilder.Entity("EMua.Models.Database.DanhGiaSanPham", b =>
                {
                    b.HasOne("EMua.Models.Database.DonHang", "MaDonHangNavigation")
                        .WithMany("DanhGiaSanPhams")
                        .HasForeignKey("MaDonHang")
                        .HasConstraintName("FK_DanhGia_DonHang");

                    b.HasOne("EMua.Models.Database.NguoiDung", "MaNguoiDungNavigation")
                        .WithMany("DanhGiaSanPhams")
                        .HasForeignKey("MaNguoiDung")
                        .HasConstraintName("FK_DG_NguoiDung");

                    b.HasOne("EMua.Models.Database.SanPham", "MaSanPhamNavigation")
                        .WithMany("DanhGiaSanPhams")
                        .HasForeignKey("MaSanPham")
                        .HasConstraintName("FK_DG_SanPham");

                    b.Navigation("MaDonHangNavigation");

                    b.Navigation("MaNguoiDungNavigation");

                    b.Navigation("MaSanPhamNavigation");
                });

            modelBuilder.Entity("EMua.Models.Database.DonHang", b =>
                {
                    b.HasOne("EMua.Models.Database.KhuyenMai", "MaKhuyenMaiNavigation")
                        .WithMany("DonHangs")
                        .HasForeignKey("MaKhuyenMai")
                        .HasConstraintName("FK_DonHang_KhuyenMai");

                    b.HasOne("EMua.Models.Database.NguoiDung", "MaNguoiDungNavigation")
                        .WithMany("DonHangs")
                        .HasForeignKey("MaNguoiDung")
                        .HasConstraintName("FK_DonHang_NguoiDung");

                    b.Navigation("MaKhuyenMaiNavigation");

                    b.Navigation("MaNguoiDungNavigation");
                });

            modelBuilder.Entity("EMua.Models.Database.HoaDon", b =>
                {
                    b.HasOne("EMua.Models.Database.DonHang", "MaDonHangNavigation")
                        .WithOne("HoaDon")
                        .HasForeignKey("EMua.Models.Database.HoaDon", "MaDonHang")
                        .IsRequired()
                        .HasConstraintName("FK_HoaDon_DonHang");

                    b.Navigation("MaDonHangNavigation");
                });

            modelBuilder.Entity("EMua.Models.Database.LichSuVanChuyen", b =>
                {
                    b.HasOne("EMua.Models.Database.DonHang", "MaDonHangNavigation")
                        .WithMany("LichSuVanChuyens")
                        .HasForeignKey("MaDonHang")
                        .IsRequired()
                        .HasConstraintName("FK_LichSuVanChuyen_DonHang");

                    b.Navigation("MaDonHangNavigation");
                });

            modelBuilder.Entity("EMua.Models.Database.NguoiDung", b =>
                {
                    b.HasOne("EMua.Models.Database.PhanQuyen", "MaQuyenNavigation")
                        .WithMany("NguoiDungs")
                        .HasForeignKey("MaQuyen")
                        .IsRequired()
                        .HasConstraintName("FK_NguoiDung_PhanQuyen");

                    b.Navigation("MaQuyenNavigation");
                });

            modelBuilder.Entity("EMua.Models.Database.SanPham", b =>
                {
                    b.HasOne("EMua.Models.Database.DanhMucSanPham", "MaDanhMucNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("MaDanhMuc")
                        .HasConstraintName("FK_SanPham_DanhMuc");

                    b.HasOne("EMua.Models.Database.ThuongHieu", "MaThuongHieuNavigation")
                        .WithMany("SanPhams")
                        .HasForeignKey("MaThuongHieu")
                        .IsRequired()
                        .HasConstraintName("FK_SanPham_ThuongHieu");

                    b.Navigation("MaDanhMucNavigation");

                    b.Navigation("MaThuongHieuNavigation");
                });

            modelBuilder.Entity("EMua.Models.Database.SanPhamHinhAnh", b =>
                {
                    b.HasOne("EMua.Models.Database.SanPham", "MaSanPhamNavigation")
                        .WithMany("SanPhamHinhAnhs")
                        .HasForeignKey("MaSanPham")
                        .IsRequired()
                        .HasConstraintName("FK_SanPhamHinhAnh_SanPham");

                    b.Navigation("MaSanPhamNavigation");
                });

            modelBuilder.Entity("EMua.Models.Database.ThanhToan", b =>
                {
                    b.HasOne("EMua.Models.Database.DonHang", "MaDonHangNavigation")
                        .WithMany("ThanhToans")
                        .HasForeignKey("MaDonHang")
                        .IsRequired()
                        .HasConstraintName("FK_ThanhToan_DonHang");

                    b.Navigation("MaDonHangNavigation");
                });

            modelBuilder.Entity("EMua.Models.Database.TinNhanAi", b =>
                {
                    b.HasOne("EMua.Models.Database.CuocHoiThoaiAi", "MaCuocHoiThoaiNavigation")
                        .WithMany("TinNhanAis")
                        .HasForeignKey("MaCuocHoiThoai")
                        .IsRequired()
                        .HasConstraintName("FK_TinNhanAI_CuocHoiThoai");

                    b.Navigation("MaCuocHoiThoaiNavigation");
                });

            modelBuilder.Entity("EMua.Models.Database.YeuThich", b =>
                {
                    b.HasOne("EMua.Models.Database.NguoiDung", "MaNguoiDungNavigation")
                        .WithMany("YeuThiches")
                        .HasForeignKey("MaNguoiDung")
                        .IsRequired()
                        .HasConstraintName("FK_YeuThich_NguoiDung");

                    b.HasOne("EMua.Models.Database.SanPham", "MaSanPhamNavigation")
                        .WithMany("YeuThiches")
                        .HasForeignKey("MaSanPham")
                        .IsRequired()
                        .HasConstraintName("FK_YeuThich_SanPham");

                    b.Navigation("MaNguoiDungNavigation");

                    b.Navigation("MaSanPhamNavigation");
                });

            modelBuilder.Entity("EMua.Models.Database.BienTheSanPham", b =>
                {
                    b.Navigation("ChiTietDonHangs");

                    b.Navigation("ChiTietGioHangs");
                });

            modelBuilder.Entity("EMua.Models.Database.CuocHoiThoaiAi", b =>
                {
                    b.Navigation("TinNhanAis");
                });

            modelBuilder.Entity("EMua.Models.Database.DanhMucSanPham", b =>
                {
                    b.Navigation("SanPhams");
                });

            modelBuilder.Entity("EMua.Models.Database.DonHang", b =>
                {
                    b.Navigation("ChiTietDonHangs");

                    b.Navigation("DanhGiaSanPhams");

                    b.Navigation("HoaDon");

                    b.Navigation("LichSuVanChuyens");

                    b.Navigation("ThanhToans");
                });

            modelBuilder.Entity("EMua.Models.Database.KhuyenMai", b =>
                {
                    b.Navigation("DonHangs");
                });

            modelBuilder.Entity("EMua.Models.Database.NguoiDung", b =>
                {
                    b.Navigation("ChiTietGioHangs");

                    b.Navigation("CuocHoiThoaiAis");

                    b.Navigation("DanhGiaSanPhams");

                    b.Navigation("DonHangs");

                    b.Navigation("YeuThiches");
                });

            modelBuilder.Entity("EMua.Models.Database.PhanQuyen", b =>
                {
                    b.Navigation("NguoiDungs");
                });

            modelBuilder.Entity("EMua.Models.Database.SanPham", b =>
                {
                    b.Navigation("BienTheSanPhams");

                    b.Navigation("DanhGiaSanPhams");

                    b.Navigation("SanPhamHinhAnhs");

                    b.Navigation("YeuThiches");
                });

            modelBuilder.Entity("EMua.Models.Database.ThuongHieu", b =>
                {
                    b.Navigation("SanPhams");
                });
#pragma warning restore 612, 618
        }
    }
}
