<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>48467100-ab8d-4347-ad71-a2042dcf1d73</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Areas\Admin\Controllers\" />
    <Folder Include="Areas\Admin\Data\" />
    <Folder Include="Areas\Admin\Models\" />
    <Folder Include="Areas\Admin\Views\" />
    <Folder Include="Areas\Staff\Controllers\" />
    <Folder Include="Areas\Staff\Data\" />
    <Folder Include="Areas\Staff\Models\" />
    <Folder Include="Areas\Staff\Views\" />
    <Folder Include="MLModels\" />
    <Folder Include="wwwroot\images\banner\" />
    <Folder Include="wwwroot\images\branchs\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.ML" Version="5.0.0" />
  </ItemGroup>

</Project>
